name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.3-openjdk-17

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: mvn compile

  test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.3-openjdk-17

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: java-app
          path: target/

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Push Docker image to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          IMAGE_TAG=my-app:$(date +%Y%m%d%H%M%S)
          docker tag my-app $IMAGE_TAG
          echo $RENDER_API_KEY | docker login --username render --password-stdin registry.render.com
          docker push $IMAGE_TAG

          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -d "{\"image\":\"$IMAGE_TAG\"}" \
          "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys"