name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.3-openjdk-17

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: mvn package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: target/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: maven:3.8.3-openjdk-17

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: java-app
          path: target/

      - name: Install Render CLI
        run: curl -fsSL https://render.com/download-cli | bash

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: ./render deploy --service-id $RENDER_SERVICE_ID --artifact target/*.jar