# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     container:
#       image: maven:3.8.3-openjdk-17

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Build with Maven
#         run: mvn package

#       - name: Upload artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: java-app
#           path: target/*.jar

#   test:
#     runs-on: ubuntu-latest
#     needs: build
#     container:
#       image: maven:3.8.3-openjdk-17

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Test with Maven
#         run: mvn test

#   deploy:
#     runs-on: ubuntu-latest
#     needs: test

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Download artifact
#         uses: actions/download-artifact@v2
#         with:
#           name: java-app
#           path: target/

#       - name: Trigger Render Deployment
#         env:
#           RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
#           RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
#         run: |
#           curl -X POST \
#           -H "Accept: application/json" \
#           -H "Authorization: Bearer $RENDER_API_KEY" \
#           -F "serviceId=$RENDER_SERVICE_ID" \
#           -T "artifact=@/home/runner/work/tp-api-spring-boot/tp-api-spring-boot/target/tpspring-0.0.1-SNAPSHOT.jar" \
#           "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys"
